// Command gendocs renders docs/rules.md, the README rule table, and the
// install-antislop skill's golangci settings asset from the analyzer
// registry. Run with -check to verify the files are current.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sanketsudake/antislop"
)

const (
	rulesPath     = "docs/rules.md"
	readmePath    = "README.md"
	settingsPath  = "skills/install-antislop/assets/golangci-settings.yml"
	startMarker   = "<!-- rules:start -->"
	endMarker     = "<!-- rules:end -->"
	settingsIntro = `# antislop settings for golangci-lint, with every option at its default.
# Generated by ` + "`make gendocs`" + ` from the analyzer registry; do not edit by hand.
#
# Merge this block into .golangci.yml under the custom linter entry, keeping
# the surrounding indentation:
#
#   linters:
#     enable: [antislop]
#     settings:
#       custom:
#         antislop:
#           type: module
#           description: Rejects low-evidence Go patterns
#           <this block>
#
# Drop the options you leave at their default. A list option is written as a
# YAML sequence here even though its command-line flag takes a comma-separated
# string, and setting it replaces the default list rather than adding to it.
`
)

func main() {
	check := flag.Bool("check", false, "verify generated files are up to date instead of writing them")
	flag.Parse()

	rules := renderRules()
	settings := renderSettings()
	readme, err := os.ReadFile(readmePath)
	if err != nil {
		fail(err)
	}
	updated, err := spliceTable(readme, renderTable(rulesPath))
	if err != nil {
		fail(err)
	}

	if *check {
		currentRules, _ := os.ReadFile(rulesPath)
		currentSettings, _ := os.ReadFile(settingsPath)
		if !bytes.Equal(currentRules, rules) ||
			!bytes.Equal(currentSettings, settings) ||
			!bytes.Equal(readme, updated) {
			fail(fmt.Errorf("generated docs are stale; run `make gendocs`"))
		}
		fmt.Println("gendocs: up to date")
		return
	}
	if err := os.WriteFile(rulesPath, rules, 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile(readmePath, updated, 0o644); err != nil {
		fail(err)
	}
	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(settingsPath, settings, 0o644); err != nil {
		fail(err)
	}
}

// renderSettings writes the settings block the golangci-lint module plugin
// reads: every analyzer, every option, every default. An analyzer with no
// options still gets an entry, so the file lists the full rule set.
func renderSettings() []byte {
	var b bytes.Buffer
	b.WriteString(settingsIntro)
	b.WriteString("settings:\n")
	b.WriteString("  # Analyzer names to leave out. Record why in a comment.\n")
	b.WriteString("  disable: []\n")
	for _, info := range antislop.Infos() {
		if len(info.Options) == 0 {
			fmt.Fprintf(&b, "  %s: {}\n", info.Name)
			continue
		}
		fmt.Fprintf(&b, "  %s:\n", info.Name)
		for _, opt := range info.Options {
			fmt.Fprintf(&b, "    # %s\n", settingsUsage(opt.Usage))
			fmt.Fprintf(&b, "    %s: %s\n", opt.Name, opt.Default)
		}
	}
	return b.Bytes()
}

// renderTable renders the rule index. docPath prefixes each anchor: the
// README links across to docs/rules.md, and that file links within itself.
func renderTable(docPath string) []byte {
	var b bytes.Buffer
	b.WriteString("| Analyzer | Rejects |\n|---|---|\n")
	for _, info := range antislop.Infos() {
		fmt.Fprintf(&b, "| [`%s`](%s#%s) | %s |\n", info.Name, docPath, info.Name, info.Summary)
	}
	return b.Bytes()
}

func renderRules() []byte {
	var b bytes.Buffer
	b.WriteString("# antislop rules\n\n")
	b.WriteString("Generated by `make gendocs` from each analyzer's `Doc`; do not edit by hand.\n\n")
	b.Write(renderTable(""))
	b.WriteString("\n")
	for _, info := range antislop.Infos() {
		fmt.Fprintf(&b, "## %s\n\n", info.Name)
		doc := strings.TrimSpace(info.Doc)
		fmt.Fprintf(&b, "%s\n\n", doc)
	}
	return b.Bytes()
}

func spliceTable(readme, table []byte) ([]byte, error) {
	start := bytes.Index(readme, []byte(startMarker))
	end := bytes.Index(readme, []byte(endMarker))
	if start < 0 || end < 0 || end < start {
		return nil, fmt.Errorf("README.md lacks %s / %s markers", startMarker, endMarker)
	}
	var b bytes.Buffer
	b.Write(readme[:start+len(startMarker)])
	b.WriteString("\n")
	b.Write(table)
	b.Write(readme[end:])
	return b.Bytes(), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gendocs:", err)
	os.Exit(1)
}

// settingsUsage rewrites a flag usage string for the YAML settings file, where
// list options are sequences rather than comma-separated strings.
func settingsUsage(usage string) string {
	return strings.Replace(usage, "comma-separated ", "list of ", 1)
}
